#!/bin/bash
# Author: Joshua Chen
# Date: 2016-02-15
# Location: Shenzhen
# Desc: Fetch the information from the service
# manager, and try to execute command on the server.

execIt() {
    unset ARGS
    i=1
    for a in "$@"
    do
        ARGS[$i]=$a
        i=$((i + 1))
    done
    pos=${#ARGS[@]}
    target=${ARGS[$pos]}
    unset ARGS[$pos]
    pos=${#ARGS[@]}
    opt=${ARGS[$pos]}
    if test "$opt" = "-s"; then
        unset ARGS[$pos]
    else
        opt=
    fi

    cmd='fetch_login_info'
    lines=$($cmd "${ARGS[@]}")
    if test -z "$lines";then
        return
    fi
    host=$(sed -n 1p <<< "$lines")
    port=$(sed -n 2p <<< "$lines")
    user=$(sed -n 3p <<< "$lines")
    password=$(sed -n 4p <<< "$lines")

    # execute
    r exec -h "$host" -P "$port" -u "$user" -p "$password" $opt "$target"
}

help() {
    echo "Usage: $(basename $0) <keyword>... <-s SCRIPT|COMMANDS>"
}

if test $# -lt 2; then
    help >&2
    exit 1
fi

execIt "$@"
