#!/bin/bash
# Author: Joshua Chen
# Date: 2016-01-30
# Location: Shenzhen
# Desc: Fetch the information from the
# service manager, and try to login.

login() {
    cmd='fetch_login_info'
    lines=$($cmd "$@")
    host=$(sed -n 1p <<< "$lines")
    port=$(sed -n 2p <<< "$lines")
    user=$(sed -n 3p <<< "$lines")
    password=$(sed -n 4p <<< "$lines")

    # login
    r shell -h "$host" -P "$port" -u "$user" -p "$password"
}

help() {
    echo "Usage: $(basename $0) <keyword>..."
}

if test $# -lt 1; then
    help >&2
    exit 1
fi

login "$@"
